Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
GuiltTripped = false
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.pci-0000_09_00.4.analog-stereo"
LastUsedOutput = ""
